end-to-end-testing:
  label: End-to-End Test
  permalink: /end-to-end-test
  description: End-to-End Test

ai-agents:
  label: AI Agents
  permalink: /ai-agents
  description: AI Agents

context-engineering:
  label: Context Engineering
  permalink: /context-engineering
  description: Context Engineering

infra:
  label: Infrastructure
  permalink: /infra
  description: Infrastructure

video-processing:
  label: Video Processing
  permalink: /video-processing
  description: Video Processing

ai:
  label: AI
  permalink: /ai
  description: Artificial Intelligence

python:
  label: Python
  permalink: /python
  description: Python Programming

automation:
  label: Automation
  permalink: /automation
  description: Automation